name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Verify uv
        run: uv --version

      - name: Sync deps
        run: |
          uv venv
          uv sync

      - name: Ruff (lint)
        run: uv run ruff .

      - name: Black (check)
        run: uv run black --check .

      - name: Pytest
        run: uv run pytest -q

      - name: Bandit (security scan)
        # Temporarily non-blocking if src/ is empty; remove '|| true' later
        run: uv run bandit -r src -ll -iii || true
